# Generated by Django 2.1.5 on 2019-03-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='date',
            new_name='DATE',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='temp_max',
            new_name='TMAX',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='temp_min',
            new_name='TMIN',
        ),
    ]
