# Generated by Django 2.1.5 on 2019-03-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0002_auto_20190314_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='weather',
            name='DATE',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
